[package]
name = "grit"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"
dirs-next = "2.0.0"
copypasta = "0.10.2"
